version: "3.8"
services:
  edc-ui:
    image: ghcr.io/sovity/edc-ui:4.1.7
    ports:
      - '11000:8080'
    environment:
      - EDC_UI_CATALOG_URLS=
      - EDC_UI_ACTIVE_PROFILE=mds-open-source
      - EDC_UI_CONFIG_URL=edc-ui-config
      - EDC_UI_MANAGEMENT_API_URL=http://localhost:11002/api/management
      - EDC_UI_MANAGEMENT_API_KEY=ApiKeyDefaultValue

  edc:
    image: ghcr.io/sovity/edc-ce-mds:10.4.2
    depends_on:
      - postgresql
    environment:
      EDC_OAUTH_TOKEN_URL: https://daps-next.test.mobility-dataspace.eu/realms/DAPS/protocol/openid-connect/token
      EDC_OAUTH_PROVIDER_JWKS_URL: https://daps-next.test.mobility-dataspace.eu/realms/DAPS/protocol/openid-connect/certs
      EDC_OAUTH_CLIENT_ID:
      MY_EDC_PARTICIPANT_ID: http://localhost:11002
      
      EDC_KEYSTORE: "/keystore.jks"
      EDC_KEYSTORE_PASSWORD: 'password'
      EDC_OAUTH_CERTIFICATE_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
    
      MY_EDC_TITLE: "MDS EDC Connector"
      MY_EDC_DESCRIPTION: "MDS EDC Connector"
      MY_EDC_CURATOR_URL: "https://example.com"
      MY_EDC_CURATOR_NAME: "Example GmbH"
      MY_EDC_MAINTAINER_URL: "https://sovity.de"
      MY_EDC_MAINTAINER_NAME: "sovity GmbH"

      MY_EDC_FQDN: "edc"
      EDC_API_AUTH_KEY: ApiKeyDefaultValue

      MY_EDC_JDBC_URL: jdbc:postgresql://postgresql:5432/edc
      MY_EDC_JDBC_USER: edc
      MY_EDC_JDBC_PASSWORD: edc

      MY_EDC_PROTOCOL: "http://"
      EDC_DSP_CALLBACK_ADDRESS: http://edc:11003/api/dsp
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,X-Api-Key'
      EDC_WEB_REST_CORS_ORIGINS: '*'

      # LH-Extension
      EDC_LOGGINGHOUSE_EXTENSION_ENABLED: 'true'
      EDC_LOGGINGHOUSE_EXTENSION_URL: https://clearing-next.test.mobility-dataspace.eu
      EDC_DATASOURCE_LOGGINGHOUSE_URL: jdbc:postgresql://postgresql:5432/edc
      EDC_DATASOURCE_LOGGINGHOUSE_USER: edc
      EDC_DATASOURCE_LOGGINGHOUSE_PASSWORD: edc
    ports:
      - '11001:11001'
      - '11002:11002'
      - '11003:11003'
      - '11004:11004'
      - '11005:5005'
    volumes:
      - ./keystore.jks:/keystore.jks

  postgresql:
    image: docker.io/bitnami/postgresql:16
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
    ports:
      - '54321:5432'
    volumes:
      - 'postgresql:/bitnami/postgresql'

volumes:
  postgresql:
    driver: local
